//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAccountant_MicrosTestProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeAccountant_MicrosTestProject.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string AddExenceTabText {
            get {
                return ResourceManager.GetString("AddExenceTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Control.
        /// </summary>
        internal static string CategoryControlGbText {
            get {
                return ResourceManager.GetString("CategoryControlGbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateProfileButtonText {
            get {
                return ResourceManager.GetString("CreateProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Create a New Profile (3-25 letters).
        /// </summary>
        internal static string CreateProfileLabelText {
            get {
                return ResourceManager.GetString("CreateProfileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Period.
        /// </summary>
        internal static string CustomPeriodTabText {
            get {
                return ResourceManager.GetString("CustomPeriodTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger Zone.
        /// </summary>
        internal static string DangerZoneGbText {
            get {
                return ResourceManager.GetString("DangerZoneGbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &amp; Drinks;Transport;Cell payment;Internet;Entertainment.
        /// </summary>
        internal static string DefaultCategoryNames {
            get {
                return ResourceManager.GetString("DefaultCategoryNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile.
        /// </summary>
        internal static string DeleteProfileButtonText {
            get {
                return ResourceManager.GetString("DeleteProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant.
        /// </summary>
        internal static string HomeFormTitle {
            get {
                return ResourceManager.GetString("HomeFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageLabelText {
            get {
                return ResourceManager.GetString("LanguageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings will be applied on the next start.
        /// </summary>
        internal static string LocaleChangeMessage {
            get {
                return ResourceManager.GetString("LocaleChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string MonthTabName {
            get {
                return ResourceManager.GetString("MonthTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherTabName {
            get {
                return ResourceManager.GetString("OtherTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ResourceCultureName {
            get {
                return ResourceManager.GetString("ResourceCultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectProfileButtonText {
            get {
                return ResourceManager.GetString("SelectProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile.
        /// </summary>
        internal static string SelectProfileLabelText {
            get {
                return ResourceManager.GetString("SelectProfileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTabText {
            get {
                return ResourceManager.GetString("SettingsTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant - Start.
        /// </summary>
        internal static string StartPageText {
            get {
                return ResourceManager.GetString("StartPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string WeekTabName {
            get {
                return ResourceManager.GetString("WeekTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string YearTabName {
            get {
                return ResourceManager.GetString("YearTabName", resourceCulture);
            }
        }
    }
}
